---
galaxy_info:
  author: ViaVitae platform team
  description: Install and configure Bitrix24 CRM in the dmz.
  company: ViaVitae IT Technologies
  license: proprietary
  min_ansible_version: "2.17"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - infrastructure
    - viavitae
  namespace: viavitae

dependencies:
  - common

